# pre-commit設定: コミット前の自動品質チェック
repos:
  # Rust標準ツール
  - repo: local
    hooks:
      - id: rust-fmt
        name: Rust format
        entry: cargo fmt --
        language: system
        files: \.rs$
        args: ["--check"]

      - id: rust-clippy
        name: Rust clippy
        entry: cargo clippy --all-targets --all-features --
        language: system
        files: \.rs$
        args: ["-D", "warnings"]

      - id: rust-test
        name: Rust test
        entry: cargo test
        language: system
        files: \.rs$
        pass_filenames: false

  # 一般的な品質チェック
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # 追加のRustツール（オプション）
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ['--verbose', '--edition', '2021']
      - id: clippy
        args: ['--all-features', '--', '-D', 'warnings']

# 設定
fail_fast: false
default_stages: [pre-commit]
